### ISSUE TITLE
A few bugs

### ISSUE THREAD

**Issue by xianshenglu** [anseki/plain-draggable#14]
1. As I saw in devtool, you delegate the` mousemove` event on `document`. If some guys use the `stopPropagation` in the container element ` mousemove` listener. The drag would not work.
So, I proposed to expose the `mousemove` element and other event delegation element.

```html
<div class="app" id="app">
  <div id="draggable">Drag This</div> 
</div>
```
```css
html,body {
  width:100%;
  height:100%;
  display:flex;
  justify-content:center;
  align-items:center;
}
.app {
  width:500px;
  height:500px;
  background:pink;
}
#draggable {
  width:100px;
  height:100px;
  background:lightblue;
  cursor:move; 
}
```
```js
var draggableIns = new PlainDraggable(draggable);
// doesn't work with code below
app.onmousemove = function() {
  event.stopPropagation();
};

```
Solution:

    1. event capture may solve this
    2. allow user to bind mousemove on other element. for example, `#app` in this case.

2. Right click would also trigger mousedown event and cause the drag behavior. I think it is not an expected behavior.

Solution:

     1. add event.button detection

I thought of these because I was making a simple draggableJs. ...
